<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $viewModel \TwoPerformant\BusinessLeagueMarketing\ViewModel\TpOrder */

$viewModel = $block->getData('tp_order');
/** @var \TwoPerformant\BusinessLeagueMarketing\ViewModel\TpOrder $viewModel */
$tpOrder = $viewModel->getTpOrder();
$slsUrl = $viewModel->getSlsUrl();
?>



    <script>
        var tpOrder =  <?= /* @noEscape */ $tpOrder; ?>;
    </script>
    <script defer src="<?= /* @noEscape */ $slsUrl; ?>"></script>
    