<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $bigBearViewModel \TwoPerformant\BusinessLeagueMarketing\ViewModel\BigBearTracker */

$bigBearViewModel = $block->getData('big_bear_view_model');
/** @var \TwoPerformant\BusinessLeagueMarketing\ViewModel\BigBearTracker $bigBearViewModel */
$tpOrder = $bigBearViewModel->getTpOrder();
$slsUrl = $bigBearViewModel->getSlsUrl();
?>



    <script>
        var tpOrder =  <?= /* @noEscape */ $tpOrder; ?>;
    </script>
    <script defer src="<?= /* @noEscape */ $slsUrl; ?>"></script>
